//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wutnu.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrlHistory
    {
        public long HistoryId { get; set; }
        public int WutLinkId { get; set; }
        public System.DateTime CallDate { get; set; }
        public string HostIp { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
        public string Country { get; set; }
        public string Continent { get; set; }
        public string Isp { get; set; }
    
        public virtual WutLink WutLink { get; set; }
    }
}
