//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wutnu.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwHistoryReport
    {
        public Nullable<int> UserId { get; set; }
        public string HitDate { get; set; }
        public string ShortUrl { get; set; }
        public string RealUrl { get; set; }
        public Nullable<int> NumHits { get; set; }
        public bool IsAzureBlob { get; set; }
        public bool IsProtected { get; set; }
    }
}
