//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wutnu.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WutLink
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WutLink()
        {
            this.UrlHistories = new HashSet<UrlHistory>();
            this.UserAssignments = new HashSet<UserAssignment>();
        }
    
        public int WutLinkId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string ShortUrl { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreatedByIp { get; set; }
        public bool IsProtected { get; set; }
        public string RealUrl { get; set; }
        public string Comments { get; set; }
        public bool IsAzureBlob { get; set; }
        public bool UseDelay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UrlHistory> UrlHistories { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserAssignment> UserAssignments { get; set; }
    }
}
