//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuditDequeue {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.2.0.0")]
    internal sealed partial class settingsTemplate : global::System.Configuration.ApplicationSettingsBase {
        
        private static settingsTemplate defaultInstance = ((settingsTemplate)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new settingsTemplate())));
        
        public static settingsTemplate Default {
            get {
                return defaultInstance;
            }
        }
    }
}
